// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZH0N5UddwtOLBjnZPiGtl7bJIXM3UJY',
    appId: '1:26321920147:web:f9ba8d7aebf26c43402d66',
    messagingSenderId: '26321920147',
    projectId: 'theavenue-reminder-hub',
    authDomain: 'theavenue-reminder-hub.firebaseapp.com',
    storageBucket: 'theavenue-reminder-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGtEyV_lIPgEmWSMexG5EhGuUg9iTJO4w',
    appId: '1:26321920147:android:a97936e2eceb211a402d66',
    messagingSenderId: '26321920147',
    projectId: 'theavenue-reminder-hub',
    storageBucket: 'theavenue-reminder-hub.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3kjiv2Ran8oUhiCJJPrOEhd7gLcbzyTo',
    appId: '1:26321920147:ios:dca0151718e8ab9c402d66',
    messagingSenderId: '26321920147',
    projectId: 'theavenue-reminder-hub',
    storageBucket: 'theavenue-reminder-hub.firebasestorage.app',
    iosBundleId: 'com.example.theAvenue',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3kjiv2Ran8oUhiCJJPrOEhd7gLcbzyTo',
    appId: '1:26321920147:ios:dca0151718e8ab9c402d66',
    messagingSenderId: '26321920147',
    projectId: 'theavenue-reminder-hub',
    storageBucket: 'theavenue-reminder-hub.firebasestorage.app',
    iosBundleId: 'com.example.theAvenue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQZH0N5UddwtOLBjnZPiGtl7bJIXM3UJY',
    appId: '1:26321920147:web:9e8b28b9f24f1b67402d66',
    messagingSenderId: '26321920147',
    projectId: 'theavenue-reminder-hub',
    authDomain: 'theavenue-reminder-hub.firebaseapp.com',
    storageBucket: 'theavenue-reminder-hub.firebasestorage.app',
  );
}
